### ISSUE TITLE
overbodige console.log in de server.js

### ISSUE THREAD

**Issue by lisagjh** [Lmikkers/user-experience-enhanced-website#1]
aan het [begin van de server.js staan 2 console logs](https://github.com/Lmikkers/user-experience-enhanced-website/blob/3c2d2d921fb9b926029d252084f4c8263a19c7a3/server.js#L1) waar eigenlijk bijna hetzelfde staat. Een van deze kan je weghalen. 

je hebt ook een [paar lijnen wit ruimte](https://github.com/Lmikkers/user-experience-enhanced-website/blob/3c2d2d921fb9b926029d252084f4c8263a19c7a3/server.js#L76), het is netter om dit weg te halen of te beperken, maar is ook persoonlijke voorkeur :)

verder ziet dit bestand er goed uit, de volgorde is logisch en de post route is na de get voor dezelfde pagina. Ook staan overal comments bij met waar het voor is.

**Comment by Lmikkers** [comment]
Top, dankjewel! Heb dit aangepast en het document geordend door de wit ruimte weg te halen en het op logische volgorde neer te zetten.
