### ISSUE TITLE
comments code in html

### ISSUE THREAD

**Issue by lisagjh** [Lmikkers/user-experience-enhanced-website#2]
https://github.com/Lmikkers/user-experience-enhanced-website/blob/3c2d2d921fb9b926029d252084f4c8263a19c7a3/views/faq.ejs#L14-L22 

Deze code staat in comments en word niet gebruikt, misschien dat je dit weg kan halen. Hierdoor ziet de html er netter en overzichtelijker uit.

https://github.com/Lmikkers/user-experience-enhanced-website/blob/3c2d2d921fb9b926029d252084f4c8263a19c7a3/views/vraag-aanbod.ejs#L15-L16 

Het is fijn dat je duidelijke uitleg geeft bij je code, zo weet ik ook waar dit voor is.

Verder is je html ook netjes geordend. Misschien kan je nog wel kijken of je voor meer dingen partials kan gebruiken?

**Comment by Lmikkers** [comment]
Heb de code netjes gemaakt, door dit weg te halen, thanks!
